# Generated by Django 2.2.2 on 2019-06-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0002_auto_20190616_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='blurb',
            field=models.CharField(default='item blurb', max_length=50),
            preserve_default=False,
        ),
    ]
