# Generated by Django 2.2.2 on 2019-06-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=50)),
                ('subrace', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alive', models.BooleanField()),
                ('barbarian', models.IntegerField()),
                ('bard', models.IntegerField()),
                ('cleric', models.IntegerField()),
                ('druid', models.IntegerField()),
                ('fighter', models.IntegerField()),
                ('monk', models.IntegerField()),
                ('paladin', models.IntegerField()),
                ('ranger', models.IntegerField()),
                ('rogue', models.IntegerField()),
                ('sorcerer', models.IntegerField()),
                ('warlock', models.IntegerField()),
                ('wizard', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Race')),
            ],
        ),
    ]
