# Generated by Django 2.2.2 on 2019-06-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_character_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='subrace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
