# Generated by Django 2.2.2 on 2019-06-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20190616_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alive',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='barbarian',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='bard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='cleric',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='druid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='fighter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='monk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='paladin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='ranger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='rogue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='sorcerer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='warlock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='wizard',
            field=models.IntegerField(default=0),
        ),
    ]
