# Generated by Django 2.2.2 on 2019-06-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190616_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alive',
            field=models.BooleanField(default=1),
        ),
    ]
