# Generated by Django 2.2.2 on 2019-06-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20190616_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='player_id',
            new_name='player',
        ),
    ]
