# Generated by Django 2.2.2 on 2019-06-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20190616_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='default name', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.Race'),
        ),
    ]
