# Generated by Django 2.2.2 on 2019-06-16 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('mission', '0002_mission_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_bool', models.BooleanField()),
                ('mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Mission')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
