# Generated by Django 2.2.2 on 2019-06-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20190616_0023'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='player_id',
        ),
        migrations.AddField(
            model_name='history',
            name='character_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.Character'),
            preserve_default=False,
        ),
    ]
