# Generated by Django 2.2.2 on 2019-06-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190616_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='character_id',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='mission_id',
            new_name='mission',
        ),
    ]
