# Generated by Django 2.2.2 on 2019-06-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
