# Generated by Django 2.2.2 on 2019-06-16 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_mission_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
